### ISSUE TITLE
Add auto feature to game

### ISSUE THREAD

**Issue by Stanley00** [dnh-bot/dnh-werewolf-bot#117]
Sometimes, player forgot to run command for action at night time and miss the chance to win. This feature will add `!auto <cmd>` command to auto execute command at specific time/phase.
Some use-case examples:

1. ~~!auto kill => Auto kill random player at end of the night if no !kill command executed~~
2. ~~!auto vote => Auto vote random player at end of the day~~
3. !auto seer => Auto seer random player, don't seer couple if Seer is one of couple
4. !auto guard => Auto guard random player
5. !auto off => Turn off auto feature, this is the default mode

**Comment by nitro2** [comment]
Done https://github.com/dnh-bot/dnh-werewolf-bot/pull/118
