### ISSUE TITLE
Change the name of `prevent_guard_self_protection` mode to avoid confusion

### ISSUE THREAD

**Issue by Stanley00** [dnh-bot/dnh-werewolf-bot#121]
This game mode config should better refactored for more clear: https://github.com/dnh-bot/dnh-werewolf-bot/blob/d7636e1ba81fcec4ff35d36a59c7f8fec1cbf558/game/text_template.py#L188

Recommend config name:   `allow_guard_self_protection`

Consider:
> `- 3. Không cho phép Bảo vệ bản thân: Tắt`

vs
> `- 3: Cho phép bảo vệ bản thân: Bật`

===========================================================================

**Comment by nitro2** [comment]
The config is saved on hard disk as true/false value. Backward compatibility can be broken. 
Need carefully handle it because we already have other users using this project :D
