### ISSUE TITLE
Add Tanner (Kẻ chán đời)

### ISSUE THREAD

**Issue by nitro2** [dnh-bot/dnh-werewolf-bot#133]
Thêm nhân vật Tanner (Kẻ chán đời)

- Chức năng: Nếu bị vote chết trong 3 ngày đầu sẽ thắng.
- Phe thứ 3 (Tanner Party)

**Comment by huybt22** [comment]
His name should be Tanner base on the traditional game

**Comment by huybt22** [comment]
Should we skip "the first 3 days" rule, so Tanner can try to distract both Werewolves and Villagers during the whole game, then it will much more fun.

I think when the 3 days ended, Tanner is just like a normal Villager which is quite boring :D

**Comment by nitro2** [comment]
So. What if noone want to vote?

**Comment by huybt22** [comment]
> So. What if noone wants to vote?

This locks Tanner into their own team and makes victory much harder for them, but also much more rewarding since it overrides any other victory.

The worst case is when Tanner get killed by Witch or Werwolves, 
he will 100% lose the game :D

**Comment by maidxn** [comment]
@huybt22 so the final decision is:
- Skip "the first three days" rules
- Tanner will be killed only by Witch or Werewolves

Am I right? Please correct me if there are more conditions or rules relative to this character, thanks.

**Comment by huybt22** [comment]
@maidxn
`
- Tanner can be killed by anything
- When Tanner is killed by `lynching`, he immediately wins the whole game, override all others win condition
`

About `three days` rule, it means Tanner must try to be lynched during the first 3 days, otherwise he will never reach the victory.

Please share your thoughts, then we can decide together.

**Comment by maidxn** [comment]
After our discussion, I wrap it up here @huybt22:

- Tanner's ability will last whole game, no limitation.
- Tanner is in Tanner party, wins game when lynched. Whenever villagers win, it still loses.

Hope this is enough what we mentioned, if there are any changes, please let me know, thanks.

**Comment by huybt22** [comment]
Agree, thank you!
