### ISSUE TITLE
Support second/minute/hour unit for timer command

### ISSUE THREAD

**Issue by nitro2** [dnh-bot/dnh-werewolf-bot#147]
Currently the timer command is not friendly for daily game
For example I have to set following config to play game daily:

```
!timer 28800 14400 14400
```

![image](https://github.com/dnh-bot/dnh-werewolf-bot/assets/3325003/33475651-b7b2-44c5-8a62-53bc88c55c1d)

28800 mean 28800 seconds = 8 hours

I want to improve the command so it can recognize all following setting:
```
!timer 120 120 60           ->  120 seconds - 120 seconds - 60 seconds
!timer 120s 120s 60s        ->  120 seconds - 120 seconds - 60 seconds
!timer 2m 2m 1m             ->  2 minutes - 2 minutes - 1 minutes
!timer 8h 4h 2h             ->  8 hours - 4 hours - 2 hours
```

Note that: After receiving the config, all minute and hour unit should convert to second in the code for the bot timer.
`Usage: !timer <dayphase-duration> <nightphase-duration> <alert-duration>`

**Comment by maidxn** [comment]
Implement in this PR https://github.com/dnh-bot/dnh-werewolf-bot/pull/156
