### ISSUE TITLE
New strategy to randomly generate roles for game

### ISSUE THREAD

**Issue by nitro2** [dnh-bot/dnh-werewolf-bot#152]
Currently we use fixed config role at `json/role_config.json` which no longer suitable for too many roles. 
We need to have new strategy to choose role for each game.

Pool:
- Fixed Role: 
  - Werewolf x 1
  - Seer x 1
  - Guard x 1
- Dynamic Role:
  - Generate Werewolf and Superwolf by rate:  1 Wolf vs 3 villagers (Including Fox and other such as Hunter.)
  - All special Role should only have 1 in game: Lycan, Betrayer, Superwolf, Fox, Witch, Zombie, Cupid, Chief, Hunter

# Generation Rule:
- If Players < 4 : Cannot start game
- If Players == 4: Return list[Werewolf, Seer, Guard, Villager]
- If Players >4:
  - https://docs.google.com/spreadsheets/d/1C7kfA44ancFW_mSKePoph1d76jKdEqHRgIyvlL4nwUo/edit#gid=0
    - Basic Roles = 3
    - Werewolf Party = math.floor(Players/4)
    - Other parties have fix range

**Comment by nitro2** [comment]
Suggestion from @Stanley00 : https://boardgamegeek.com/thread/641590/article/6606245#6606245
```
+7 Seer
+4 Apprentice, Witch, Magician
+3 Hunter, Diseased, Martyr, Tough Guy, Aura Seer, Priest, Bodyguard, PI, Prince
+2 Troublemaker, Ghost, Mayor, Mason, Idiot
+1 Villager, Spellcaster, Tanner, Cult Leader,Old Hag
0 Hoodlum, Old Man
-1 Lycan
-2 Doppelganger, Pacifist
-3 Cupid, Drunk, Cursed, Sorcerer
-5 Lone Wolf
-6 Werewolf, Minion
-7 Vampire
-8 Wolf Cub
```

**Comment by Stanley00** [comment]
Sample code for generate roles based on pre-defined scores: [tio.run](https://tio.run/##fVJda9swFH2OfsWlL5YbZ03abINQ72HZVyFQaMcKCyao9nUskCVzLdOGsd@eSUptdw/bm87VuedcnavmYCujr45HWTeGLJDQhalZSaaG3CiFuZVGt/ByvTadtkiM3d1uPu8@3ay/Qwq/GJz9kEqJPdLZChaJww9I@GRU6fDsrS/cY7gM56@doMKBKw82h1xoTwt9H9GSOATq7DL0dQ1Sr/TeV76Y54H@IG1eOfTOg5@mfpTY6667RnqT2QlVEr1E0PwWHuGJ7DdjrMAS9mh3bW4IORmFbbxiE0LbkYa2q/nw2i1lUBoCAqnhxOz79c5jrhMo5TMWAaXbqA8iyhKoXLgyF006T6BAZUW68EaibZEsX16nOmYTDbMUFGo@yjiPSRhhc3PvA1eytZzGQcZlyNJVtLG@@nf/UyUVBt1BKb7W55fO/5X2NIVXIycQhe1EGUxdvd9xlJ0vneLpq7xpq64s3cNH2d5MPLZ8zHUcx4kN5O1KZ7Er9NHE8OEUjZ/r3w7DdlyT5S@/8n8WrsXHJcPehN4jX8znPvyGpLZ8WN9yKi8uFnPHn7Dj8Q8)

**Comment by huybt22** [comment]
Suggested flow
```
1. Setup bộ role

- Lấy các roles sói, 25% sói, số sói max là 5. Handle 1 số điều kiện cơ bản
- Lấy các roles còn lại, có điều kiện phù hợp vd Fox chỉ khi players > 8,...
- Fill Villager vào nếu còn thiếu

Shuffle...

2. Fix theo bộ role đã shuffle cho phù hợp
- Vd có sói con có phản bội nhưng lại ko có sói nào -> Pick random sói bỏ vào
- Vd có tri tập sự nhưng ko có seer -> Thêm vào
...

3. Check flag balance
- Check đảm bảo có 2 team, 1 phe solo
- Check phe ác < phe dân
- Tính tổng điểm, điểm 1 số role có thể dynamic cho phù hợp mà ko hardcode
- Check balance: (phe dân - phe ác) <= (tổng players/4 +1)
..... Các đk balance khác.....

Tiếp tục random nếu chưa balanced

```
