### ISSUE TITLE
Should have predefined admin list

### ISSUE THREAD

**Issue by Stanley00** [dnh-bot/dnh-werewolf-bot#183]
The bot should have predefined admin list. These users can use admin commands without Admin role.

**Comment by huybt22** [comment]
Should the admins then able to add more admin in json file while runtime? 😃

**Comment by huybt22** [comment]
Should the admins then able to add more admin in json file while runtime? 😃

**Comment by Stanley00** [comment]
I didn't think of it, but that should be done by higher admin role?
