### ISSUE TITLE
New character - Kẻ bị Nguyền rủa (Cursed)

### ISSUE THREAD

**Issue by nitro2** [dnh-bot/dnh-werewolf-bot#208]
![image](https://github.com/dnh-bot/dnh-werewolf-bot/assets/3325003/0b870050-a66e-4d4d-9019-956fa7471cd2)

Kẻ bị Nguyền rủa ban đầu là người, Tiên tri soi cũng ra người. Nếu Kẻ bị Nguyền rủa bị Sói cắn thì sẽ không chết, mà từ đêm tiếp theo sẽ biến thành Sói, đồng thời nếu Tiên tri soi thì cũng sẽ là Sói. Kẻ bị Nguyền rủa mỗi đêm được gọi dậy riêng biệt, kể cả sau khi hóa Sói, để cho người này biết đã bị hóa Sói hay chưa.

Trong trường hợp Kỹ Nữ ngủ với Bán Sói => Nếu đêm đó Sói tấn công Bán Sói thì Bán Sói sẽ lập tức DIE thay vì trở thành Ma Sói

**Comment by Stanley00** [comment]
> Kẻ bị Nguyền rủa mỗi đêm được gọi dậy riêng biệt, kể cả sau khi hóa Sói, để cho người này biết đã bị hóa Sói hay chưa.

Phần này sẽ không cần vì chơi online, mình có thể nhắn riêng và add vào channel của sói là xong, sẽ không sợ bị lộ.

**Comment by Stanley00** [comment]
> Trong trường hợp Kỷ Nữ ngủ với Bán Sói => Nếu đêm đó Sói tấn công Bán Sói thì Bán Sói sẽ lập tức DIE thay vì trở thành Ma Sói

Role này nên để sau khi có role Kỹ nữ mình sẽ implement sau

**Comment by neihousaigaai** [comment]
## Checklist for Cursed role

### Help text

- [ ] Update `json/role_info.json`
- [ ] Update `json/command_info.json`
- [ ] Update `STORY_VN.md`

### Code

- [ ] Create the `Cursed` role class inside `game/roles/cursed.py` file
- [ ] Add `Cursed` class to `get_all_roles()` return result (inside `game/roles/__init__.py` file)
- [ ] Add new `cursed_do_(new|end)_(day|night)time_phase` function in `game/__init__.py` (if needed)
- If the new role has its command(s):
    - [ ] Add new command(s) in `commands/command.py`
    - [ ] Add new command action function(s) in `game/__init__.py`
- [ ] Update `json/text_template.json`

### Role generator

- [ ] Add `Cursed` role point into `json/role_generator_info.json`
- [ ] Update `game/generate_roles.py` (if needed)
- [ ] Update `json/role_config.json` with the new role
- [ ] Run `evaluate_system()` inside `game/calc_points.py` and make sure the new role has been generated.

### Test cases

- [ ] simple test (follow specs)
- special cases (listed below)
    - [ ] the new role in a couple
    - [ ] the new role has a relation with other roles
