### ISSUE TITLE
New Character - ApprenticeSeer (Tiên tri tập sự)

### ISSUE THREAD

**Issue by nitro2** [dnh-bot/dnh-werewolf-bot#210]
![image](https://github.com/dnh-bot/dnh-werewolf-bot/assets/3325003/6a74114d-3525-496f-b89b-595a798f5a6c)
Nếu Tiên tri đã bị loại khỏi cuộc chơi, nhân vật này sẽ trở thành Tiên tri.

**Comment by neihousaigaai** [comment]
## Checklist for new role

### Help text

- [ ] Update `json/role_info.json`
- [ ] Update `json/command_info.json`
- [ ] Update `STORY_VN.md`

### Code

- [ ] Create the new role class inside `game/roles/<rolename>.py` file
- [ ] Add new role class to `get_all_roles()` return result (inside `game/roles/__init__.py` file)
- [ ] Add new `<rolename>_do_(new|end)_(day|night)time_phase` function in `game/__init__.py` (if needed)
- If the new role has its command(s):
    - [ ] Add new command(s) in `commands/command.py`
    - [ ] Add new command action function(s) in `game/__init__.py`
- [ ] Update `json/text_template.json`

### Role generator

- [ ] Add new role point into `json/role_generator_info.json`
- [ ] Update `game/generate_roles.py` (if needed)
- [ ] Update `json/role_config.json` with the new role
- [ ] Run `evaluate_system()` inside `game/calc_points.py` and make sure the new role has been generated.

### Test cases

- [ ] simple test (follow specs)
- special cases (listed below)
    - [ ] the new role in a couple
    - [ ] the new role has a relation with other roles
