### ISSUE TITLE
New Character - Rat (Chuột ma sói)

### ISSUE THREAD

**Issue by nitro2** [dnh-bot/dnh-werewolf-bot#232]
Ref: Chuột ma sói https://vnexpress.net/chuot-ma-soi-chuyen-an-bo-cap-va-ret-doc-4736959.html

- Thuộc phe ma sói nhưng không biết ai là sói
- Mỗi đêm có thể cắn chết một người 
  - Nếu cắn trúng Fox hoặc Guard sẽ chết
  - Dùng lệnh `.bite <id>` để cắn người
  - Seer sẽ soi ra là sói

**Comment by hthanhdev** [comment]
Thuộc phe: 
- [X] Sói
- [ ] Người
- [ ] Khác

Có thấy role người khác không :
- [ ] Có
- [X] Không

Người khác thấy role bản thân không:
- [ ] Có
- [X] Không

Seer sẽ soi ra 
- [X] Sói
- [ ] Người
- [ ] Khác

Ban ngày:
* Chỉ được vote

Ban đêm
* Được cắn 1 người, người đó chết nếu là `Fox` hoặc `Guard`

Câu lệnh `.bite <id>`

**Comment by neihousaigaai** [comment]
- Nếu Sói cắn Diseased, chỉ có toàn bộ Sói bị nhiễm bệnh, không ảnh hưởng đến Rat
- Nếu Rat cắn Diseased, cả 2 sẽ chết. Tuy nhiên nếu Diseased được bảo vệ thì Rat chỉ bị bệnh (và không cắn được ai vào đêm hôm sau).
