### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by kaniki00** [dnh-bot/dnh-werewolf-bot#51]
Các nhân vật khác có thể thêm:

Witch (Phù thủy)
Apprentice Seer (Tiên tri tập sự): Khi tiên tri chết, thì tiên tri tập sự sẽ trở thành tiên tri mới
Thần tình yêu Cupid
Diseased (Người bệnh): nếu sói cắn trúng, thì đêm tiếp theo sói không thể cắn người do bị lây bệnh
Wolf Cub (Sói con): nếu sói con chết, sói sẽ được cắn 2 người trong đêm tiếp theo
Sorceress (Pháp sư sói): có thể kiểm tra 1 người xem có phải tiên tri mỗi đêm hay không. Chiến thắng cùng phe sói. Nhưng pháp sư sói và sói không được biết nhau
Relatives (họ hàng): biến thể của Hai chj em và Ba anh em: là dân làng bình thường, nhưng có thể biết được nhau
Cáo: thuộc phe thứ ba, cáo sẽ chiến thắng nếu tất cả sói bị giết

**Comment by neihousaigaai** [comment]
This content is not an issue and I don't know who you are.
